### PR TITLE
Switch cvitjs to use the libraries api.

### PR DESCRIPTION
**Pull request by laceysanderson**
Here's the promised PR for libraries api support of cvitjs. I've tested it on my system and it works beautifully. It does depend on a PR for CViTjs changing the path in the require.js blastui.conf.

### CODE REVIEW

**Comment by laceysanderson** [comment]
Ooops, need to update help docs first

**Comment by laceysanderson** [comment]
There. Now this PR should be ready to go. The CViTjs PR has already been merged so just make sure to clone the most recent code when testing :-)

**Comment by ekcannon** [comment]
Appears to be working with one exception:
_dependencies[] = libraries_api_
Produces an error when attempting to enable the module, even though Libraries API is present and enabled. This worked:
_dependencies[] = libraries_

'libraries' vs 'libraries_api' ... what's the difference?

**Comment by laceysanderson** [comment]
Shoot! That's a stupid mistake on my part *head slap*. It's supposed to be `dependencies[] = libraries`

**Comment by laceysanderson** [comment]
Fixed! Good catch!

**Pull request merged**
